name: Pumba CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  full:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1

    - name: decide on Docker image tag
      run: |
        echo $GITHUB_REF | sed -e 's/refs\/heads\///g' -e 's/refs\/tags\///g' | sed -e 's/master/latest/g' > IMAGE_TAG
        echo "Tagging image with '$(cat IMAGE_TAG)'"

    - name: build test images
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        DOCKER_BUILDKIT: 1
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)

        echo "==> compile and test Go code"
        docker build -t pumba/build-and-test --target build-and-test --build-arg CODECOV_TOKEN=${CODECOV_TOKEN} --build-arg VCS_COMMIT_ID=${GITHUB_SHA} --build-arg VCS_BRANCH_NAME=${IMAGE_TAG} --build-arg VCS_SLUG=${GITHUB_REPOSITORY} -f docker/Dockerfile .

        echo "==> prepare integration tests image"
        docker build -t pumba/integration-tests --target integration-tests --build-arg CODECOV_TOKEN=${CODECOV_TOKEN} --build-arg VCS_COMMIT_ID=${GITHUB_SHA} --build-arg VCS_BRANCH_NAME=${IMAGE_TAG} --build-arg VCS_SLUG=${GITHUB_REPOSITORY} -f docker/Dockerfile .

    - name: run integration tests
      run: |
        docker run -i --rm --name integration-tests pumba/integration-tests

    - name: upload coverage report
      run: |
        CI_BUILD_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks
        docker run -i --rm --name upload-coverage -e CI_BUILD_URL=${CI_BUILD_URL} -e CI_BUILD_ID=${RUNNER_TRACKING_ID} pumba/build-and-test

    # - name: push Docker image
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |
    #     IMAGE_TAG=$(cat IMAGE_TAG)
    #     echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    #     docker push ${DOCKER_USERNAME}/pumba:${IMAGE_TAG}
    #     docker logout
