name: Pumba CI

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:

  full:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1

    - name: debug
      run: printenv

    - name: decide on Docker image tag
      run: |
        echo ${{ github.ref }} | sed -e 's/^refs\/heads\///g' -e 's/^refs\/tags\///g' -e 's/^refs\/pull\///g' -e 's/\/merge$//g' | sed -e 's/master/latest/g' > IMAGE_TAG
        echo "Tagging image with '$(cat IMAGE_TAG)'"

    - name: prepare build arguments
      run: |
        echo "--progress=plain --build-arg=CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} --build-arg=VCS_COMMIT_ID=${{ github.sha }} --build-arg=VCS_BRANCH_NAME=${IMAGE_TAG} --build-arg=VCS_SLUG=${{ github.repository }} --build-arg=GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }} --file=docker/Dockerfile ." > BUILD_ARGS

    - name: build test images
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)

        echo "==> compile and test Go code"
        DOCKER_BUILDKIT=1 docker build --tag=pumba/build-and-test --target=build-and-test $(cat BUILD_ARGS)
        echo "==> prepare integration tests image"
        DOCKER_BUILDKIT=1 docker build --tag pumba/integration-tests --target=integration-tests $(cat BUILD_ARGS)

    - name: run integration tests
      run: |
        docker run -i --rm --name integration-tests -v /var/run/docker.sock:/var/run/docker.sock pumba/integration-tests

    - name: upload coverage report
      run: |
        CI_BUILD_URL=https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        docker run -i --rm --name upload-coverage -e CI_BUILD_URL=${CI_BUILD_URL} -e CI_BUILD_ID=${RUNNER_TRACKING_ID} pumba/build-and-test

    - name: prepare final image
      if: github.event_name != 'pull_request'
      env:
        DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)
        DOCKER_BUILDKIT=1 docker build --tag=${DOCKER_ACCOUNT}/pumba:${IMAGE_TAG} $(cat BUILD_ARGS)

    - name: push Docker image
      if: github.event_name != 'pull_request'
      env:
        DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)
        echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_ACCOUNT} --password-stdin
        docker push ${DOCKER_ACCOUNT}/pumba:${IMAGE_TAG}
        docker logout

    - name: release to GitHub
      if: github.event_name != 'pull_request'
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)
        if [[ "${IMAGE_TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then DOCKER_BUILDKIT=1 docker build --tag pumba/github-release --target=github-release $(cat BUILD_ARGS); fi
