name: "Release to GitHub"

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - 'deploy/**'
      - '*.md'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: decide on tag
        id: tagger
        run: |
          tag=$(echo "${{ github.ref }}" | sed -e 's/^refs\/heads\///g' -e 's/^refs\/tags\///g' -e 's/^refs\/pull\///g' -e 's/\/merge$//g' | sed -e 's/master/latest/g')
          echo "::set-output name=tag::${tag}"
          echo "::debug::docker image tag ${tag}"

      - name: release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          context: .
          build-args: |
            RELEASE=true
            RELEASE_TAG=${{ steps.tagger.outputs.tag }}
            RELEASE_TOKEN=${{ secrets.RELEASE_TOKEN }}
            TAG_MESSAGE="Draft Release"
            GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }}
            VCS_COMMIT_ID=${{ github.sha }}
            VCS_BRANCH_NAME=${{ steps.tagger.outputs.tag }}
            VCS_SLUG=${{ github.repository }}
          target: github-release
